<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="conveyor_belt">
    
    <!-- Conveyor Belt Properties -->
    <xacro:property name="belt_length" value="2.0"/>
    <xacro:property name="belt_width" value="0.5"/>
    <xacro:property name="belt_height" value="0.05"/>
    <xacro:property name="belt_speed" value="0.1"/>
    
    <!-- Support Structure Properties -->
    <xacro:property name="support_height" value="0.8"/>
    <xacro:property name="support_width" value="0.1"/>
    
    <!-- Conveyor Belt Base -->
    <link name="conveyor_base">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${belt_length} ${belt_width} ${belt_height}"/>
            </geometry>
            <material name="belt_material">
                <color rgba="0.2 0.2 0.2 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${belt_length} ${belt_width} ${belt_height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="50.0"/>
            <inertia ixx="4.17" ixy="0" ixz="0" iyy="16.67" iyz="0" izz="20.83"/>
        </inertial>
    </link>
    
    <!-- Support Structure Left -->
    <link name="support_left">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${support_width} ${support_width} ${support_height}"/>
            </geometry>
            <material name="support_material">
                <color rgba="0.8 0.8 0.8 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${support_width} ${support_width} ${support_height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="10.0"/>
            <inertia ixx="0.53" ixy="0" ixz="0" iyy="0.53" iyz="0" izz="0.017"/>
        </inertial>
    </link>
    
    <!-- Support Structure Right -->
    <link name="support_right">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${support_width} ${support_width} ${support_height}"/>
            </geometry>
            <material name="support_material">
                <color rgba="0.8 0.8 0.8 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${support_width} ${support_width} ${support_height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="10.0"/>
            <inertia ixx="0.53" ixy="0" ixz="0" iyy="0.53" iyz="0" izz="0.017"/>
        </inertial>
    </link>
    
    <!-- Joints -->
    <joint name="support_left_joint" type="fixed">
        <parent link="conveyor_base"/>
        <child link="support_left"/>
        <origin xyz="${-belt_length/2 + support_width/2} ${belt_width/2 + support_width/2} ${-support_height/2 - belt_height/2}" rpy="0 0 0"/>
    </joint>
    
    <joint name="support_right_joint" type="fixed">
        <parent link="conveyor_base"/>
        <child link="support_right"/>
        <origin xyz="${belt_length/2 - support_width/2} ${belt_width/2 + support_width/2} ${-support_height/2 - belt_height/2}" rpy="0 0 0"/>
    </joint>
    
    <!-- Gazebo Properties for Belt Movement -->
    <gazebo reference="conveyor_base">
        <material>Gazebo/DarkGrey</material>
        <mu1>0.8</mu1>
        <mu2>0.8</mu2>
        <kp>1000000.0</kp>
        <kd>100.0</kd>
        <minDepth>0.001</minDepth>
        <maxVel>1.0</maxVel>
        <fdir1>1 0 0</fdir1>
    </gazebo>
    
    <gazebo reference="support_left">
        <material>Gazebo/Grey</material>
    </gazebo>
    
    <gazebo reference="support_right">
        <material>Gazebo/Grey</material>
    </gazebo>

</robot>
